### PR TITLE
Modularize Cardboard and push latest version

### LINKED ISSUE #54: Dependencies not linked to requirements.txt
These dependencies are currently not linked to [requirements.txt](https://github.com/RobinsMediaTeam/Cardboard/blob/master/requirements.txt). We should link them in the coming time.

_Originally posted by @JeffreyBlinksma in https://github.com/RobinsMediaTeam/Cardboard/pull/48#discussion_r1040079923_

### PR DESCRIPTION
**Pull request by JeffreyBlinksma**

### CODE REVIEW

**Comment by JeffreyBlinksma** [comment]
Has yet to be tested.

**Comment by JeffreyBlinksma** [comment]
Errors out with
```Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    import pyodbc
ModuleNotFoundError: No module named 'pyodbc'

**Comment by JeffreyBlinksma** [comment]
Downgrading to Python 3.10.9 has temporarily fixed this, allowing us to merge this pull request. This should be fixed in a future PR.

**Review by ThatOneNovaGuy — APPROVED** [review]
`sepay.py` could use improvement, but this can be done in a later PR. The primary objective of this one is updating the repository to the live dev build.

**Pull request merged**
